### ISSUE TITLE
Menda themes issues

### ISSUE THREAD

**Issue by sergioad** [anexation/menda-icon-themes#1]
Hello I found some issues with the Menda icons

1.- the bluetooth tray item does not has an icon for it's turned off state
2.- the Menda square does not have the major part of it's icons; inmediat fix is needed I love the squared themes

**Comment by anexation** [comment]
menda square and menda circle are the same except for the applicaion icons in each which i dont maintain.. I maintain all the icons but application icons which i get from up stream numix.. And i will look into the bluetooth turned off state diff..

**Comment by sergioad** [comment]
I know that but many of the icons are missing and the same icons are present on the Numix circle and square

![captura de pantalla - 241114 - 08 20 06](https://cloud.githubusercontent.com/assets/5375145/5166118/c8052ace-73b2-11e4-9687-e93ca08dfb42.png)
No better form to explain the issue :smile:

**Comment by anexation** [comment]
![image](https://cloud.githubusercontent.com/assets/6136025/5168579/0bb8cbc8-73c6-11e4-8b6d-510642a157a1.png)

here you go buddy. Have a good day and enjoy

**Comment by sergioad** [comment]
Cool thank you so much; when will be ready for upgrade on Manjaro?
