### ISSUE TITLE
Copyright infrigement

### ISSUE THREAD

**Issue by satya164** [anexation/menda-icon-themes#12]
This icon theme includes a lot of icons from the Numix Square icon theme. The License of Numix Square doesn't allow you to distribute or re-license the icons. The specific phrase from the License is,

The license granted above is expressly made subject to and limited by the
following restrictions:

```
   1. You may not Re-Distribute the Work in its original form.
   2. You may not Distribute Modification(s) of the Work without the
      explicit permission of the Licensor.
   4. You may not use the Work towards commercial advantage or private
      monetary compensation.
```

Please remove all the icons used from the Numix Square icon theme within 3 days. Or we'll be forced to file a DCMA takedown.

**Comment by Foggalong** [comment]
+1
