### ISSUE TITLE
Licensing for Flattr based elements in Menda.

### ISSUE THREAD

**Issue by UriHerrera** [anexation/menda-icon-themes#5]
While I know not all of the theme is based off Flattr (I've downloaded it), some of it's elements are, and there's some issues with it:

I see no mention what's the Licensing for this derivative, and no mention _either_ of Crediting the original authors (not just of Flattr by the way), something that at least for Flattr based themes it's a requirement of the license - https://github.com/NitruxSA/flattr-icons/blob/master/LICENSE.

> Share Alike —  If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
> 
> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use

As mentioned above, derivative works must use the **same** license, I could only find information about it from the PKGBLD: https://github.com/manjaro/packages-extra/blob/master/menda-icon-themes/PKGBUILD - which states the License is GPL, which would be wrong, at least for the Flattr derived elements, you cannot re-license the elements you used.

Once the requirements are met you are indeed able to do whatever you want with them :)

**Comment by anexation** [comment]
https://github.com/anexation/menda-icon-themes/blob/master/CREDIT
https://github.com/anexation/menda-icon-themes/blob/master/LICENSE

Hope this meets the requirements, I should of gotten to this sooner.

**Comment by UriHerrera** [comment]
Sure, thank you!.
